custom:
  email:
    messages:
      verification: |
        ???????? ?? ?????? ??? ????????? ???????? ? ?????????? search-realty 
        http://rent-test.by/realty/api/users/verification?email=%s&token=%s
      updatePassword: |
        ???????? ?? ?????? ??? ?????????????? ?????? ? ?????????? search-realty
        ???? ?? ?? ??????????? ????? ?????? ? ??????????, ??????????, ??????????? ?????? ??????.  
        http://rent-test.by/realty/forgot-password?token=%s
