custom:
  email:
    messages:
      verification: |
        follow the link below to complete the verification process in the application search-realty 
        http://rent-test.by/realty/api/users/verification?email=%s&token=%s
      updatePassword: |
        follow the link bellow to change your password in the application search-realty
        If you do not want change the password in the application, then ignore this letter.  
        http://rent-test.by/realty/forgot-password?token=%s
