spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://user-database:5432/user
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    deserialization:
      read-unknown-enum-values-as-null: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: orgalexeysearchrealty@gmail.com
    password: ${REALTY_EMAIL_PASSWORD}
    app-password: ${REALTY_EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 80
  servlet:
    context-path: "/realty/api"

custom:
  jwt:
    secret: QAZ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYz
    issuer: org.alexey
  feign:
    audit-logs:
      url: http://audit-service:80/realty/api
  email:
    messages:
      verification: |
        follow the link below to complete the verification process in the application search-realty 
        http://user-service:80/realty/api/users/verification?email=%s&token=%s
      updatePassword: |
        follow the link bellow to change your password in the application search-realty
        If you do not want change the password in the application, then ignore this letter.  
        http://user-service:80/realty/forgot-password?token=%s