package rentconfigservice.core.entity;

public enum AuditedAction {
 REGISTRATION,
 VERIFICATION,
 LOGIN,
 INFO_ABOUT_ME,
 UPDATE_PASSWORD,
 INFO_ABOUT_ALL_USERS,
 INFO_ABOUT_USER_BY_ID,
 CREATE_USER,
 UPDATE_USER
}
